// GERADO AUTOMATICAMENTE — não editar à mão.
// Fonte: docs/Sistema - Base de Cadastro de Clientes.xlsx
// Gerado em 11/09/2026 por docs/tools/gerar-catalogo-dominios.py
//
// Fonte única dos domínios e notas do cadastro de clientes (ORDEM-02,
// solução S1.2). Consumido pelo formulário, pelo importador, pelo motor
// de complexidade e pelo agente de IA. Para alterar: mexer na planilha
// e rodar o gerador novamente.

import {
  CatalogField,
  ComplexityFront,
} from './client-catalog.types';

export const CATALOG_SOURCE = {
  file: 'Sistema - Base de Cadastro de Clientes.xlsx',
  generatedAt: '11/09/2026',
};

export const CATALOG_FIELDS: CatalogField[] = [
  {
    key: 'MESTRE__DATA_DE_INICIO_OPERACAO',
    number: 1,
    block: 'MESTRE',
    label: 'Data de Início (Operação)',
    type: 'MASCARA',
    format: 'DATA',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__CICLO_AAAA_MM',
    number: 2,
    block: 'MESTRE',
    label: 'Ciclo (AAAA-MM)',
    type: 'MASCARA',
    format: 'DATA',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__CNPJ_CPF',
    number: 3,
    block: 'MESTRE',
    label: 'CNPJ/CPF',
    type: 'MASCARA',
    format: 'DOCUMENTO',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__PERFIL_DO_CLIENTE',
    number: 4,
    block: 'MESTRE',
    label: 'Perfil do Cliente',
    type: 'LISTA',
    role: 'CC',
    pillar: 'Perfil jurídico/operacional',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
    options: [
      { value: 'EMPRESA_PJ', label: 'Empresa – PJ', cc: { FISCAL: 3, CONTABIL: 3, PESSOAL: 3 } },
      { value: 'PRODUTOR_RURAL_PF', label: 'Produtor Rural – PF', cc: { FISCAL: 4, CONTABIL: 3, PESSOAL: 3 } },
      { value: 'PESSOA_FISICA', label: 'Pessoa Física', cc: { FISCAL: 1, CONTABIL: 1, PESSOAL: 1 } },
      { value: 'EMPREGADOR_DOMESTICO', label: 'Empregador Doméstico', cc: { FISCAL: 1, CONTABIL: 1, PESSOAL: 1 } },
    ],
  },
  {
    key: 'MESTRE__RAZAO_SOCIAL_NOME',
    number: 5,
    block: 'MESTRE',
    label: 'Razão social/Nome',
    type: 'TEXTO',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__NOME_FANTASIA',
    number: 6,
    block: 'MESTRE',
    label: 'Nome fantasia',
    type: 'TEXTO',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__STATUS_CONTRATO',
    number: 7,
    block: 'MESTRE',
    label: 'Status contrato',
    type: 'LISTA',
    role: 'ELEGIBILIDADE',
    pillar: 'Status / elegibilidade',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
    options: [
      { value: 'ATIVO', label: 'Ativo' },
      { value: 'SEM_MOVIMENTO', label: 'Sem Movimento' },
      { value: 'INATIVA', label: 'Inativa' },
    ],
  },
  {
    key: 'MESTRE__SEGMENTO',
    number: 8,
    block: 'MESTRE',
    label: 'Segmento',
    type: 'LISTA',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
    options: [
      { value: 'AGRONEGOCIO', label: 'Agronegócio' },
      { value: 'ALIMENTACAO_HOTELARIA_E_TURISMO', label: 'Alimentação, Hotelaria e Turismo' },
      { value: 'COMERCIO_E_DISTRIBUICAO', label: 'Comércio e Distribuição' },
      { value: 'CONSTRUCAO_E_MERCADO_IMOBILIARIO', label: 'Construção e Mercado Imobiliário' },
      { value: 'EDUCACAO', label: 'Educação' },
      { value: 'ENTIDADES_CONDOMINIOS_E_TERCEIRO_SETOR', label: 'Entidades, Condomínios e Terceiro Setor' },
      { value: 'FINANCEIRO_SEGUROS_E_INVESTIMENTOS', label: 'Financeiro, Seguros e Investimentos' },
      { value: 'HOLDINGS_E_PATRIMONIAL', label: 'Holdings e Patrimonial' },
      { value: 'INDUSTRIA', label: 'Indústria' },
      { value: 'PESSOA_FISICA_E_EMPREGADOR_DOMESTICO', label: 'Pessoa Física e Empregador Doméstico' },
      { value: 'SAUDE_E_BEM_ESTAR', label: 'Saúde e Bem-Estar' },
      { value: 'SERVICOS_EMPRESARIAIS_E_PROFISSIONAIS', label: 'Serviços Empresariais e Profissionais' },
      { value: 'TECNOLOGIA_E_COMUNICACAO', label: 'Tecnologia e Comunicação' },
      { value: 'TRANSPORTE_E_LOGISTICA', label: 'Transporte e Logística' },
      { value: 'OUTROS', label: 'Outros' },
    ],
  },
  {
    key: 'MESTRE__REGIME_TRIBUTARIO',
    number: 9,
    block: 'MESTRE',
    label: 'Regime tributário',
    type: 'LISTA',
    role: 'CC',
    pillar: 'Regime tributário',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront],
    options: [
      { value: 'IMUNE_OU_ISENTA', label: 'Imune ou Isenta', cc: { FISCAL: 4, CONTABIL: 4 } },
      { value: 'LUCRO_PRESUMIDO', label: 'Lucro Presumido', cc: { FISCAL: 3, CONTABIL: 3 } },
      { value: 'LUCRO_REAL', label: 'Lucro Real', cc: { FISCAL: 5, CONTABIL: 5 } },
      { value: 'REGIME_ESPECIAL', label: 'Regime Especial', cc: { FISCAL: 5, CONTABIL: 5 } },
      { value: 'SIMPLES', label: 'Simples', cc: { FISCAL: 1, CONTABIL: 1 } },
    ],
  },
  {
    key: 'MESTRE__HONORARIO_FATURADO',
    number: 10,
    block: 'MESTRE',
    label: 'Honorário faturado',
    type: 'MASCARA',
    format: 'VALOR',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__FAIXA_FATURAMENTO_ANUAL',
    number: 11,
    block: 'MESTRE',
    label: 'Faixa faturamento anual',
    type: 'LISTA',
    role: 'CC',
    pillar: 'Porte',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront],
    options: [
      { value: 'ATE_R_360_MIL', label: 'Até R$ 360 mil', cc: { FISCAL: 1, CONTABIL: 1 } },
      { value: 'R_360_MIL_1_2_MI', label: 'R$ 360 mil–1,2 mi', cc: { FISCAL: 2, CONTABIL: 2 } },
      { value: 'R_1_2_4_8_MI', label: 'R$ 1,2–4,8 mi', cc: { FISCAL: 3, CONTABIL: 3 } },
      { value: 'R_4_8_20_MI', label: 'R$ 4,8–20 mi', cc: { FISCAL: 4, CONTABIL: 4 } },
      { value: 'R_20_78_MI', label: 'R$ 20–78 mi', cc: { FISCAL: 5, CONTABIL: 5 } },
      { value: 'ACIMA_DE_R_78_MI', label: 'Acima de R$ 78 mi', cc: { FISCAL: 5, CONTABIL: 5 } },
    ],
  },
  {
    key: 'MESTRE__CLASSIFICACAO_A_D',
    number: 12,
    block: 'MESTRE',
    label: 'Classificação A-D',
    type: 'LISTA',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
    options: [
      { value: 'A', label: 'A' },
      { value: 'B', label: 'B' },
      { value: 'C', label: 'C' },
      { value: 'D', label: 'D' },
    ],
  },
  {
    key: 'MESTRE__FISCAL',
    number: 13,
    block: 'MESTRE',
    label: 'Fiscal?',
    type: 'SWITCH',
    role: 'ELEGIBILIDADE',
    pillar: 'Frente contratada',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__CONTABIL',
    number: 14,
    block: 'MESTRE',
    label: 'Contábil?',
    type: 'SWITCH',
    role: 'ELEGIBILIDADE',
    pillar: 'Frente contratada',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__PESSOAL',
    number: 15,
    block: 'MESTRE',
    label: 'Pessoal?',
    type: 'SWITCH',
    role: 'ELEGIBILIDADE',
    pillar: 'Frente contratada',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'MESTRE__OBSERVACOES_GERAIS',
    number: 16,
    block: 'MESTRE',
    label: 'Observações - Gerais',
    type: 'TEXTO',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront, 'CONTABIL' as ComplexityFront, 'PESSOAL' as ComplexityFront],
  },
  {
    key: 'FISCAL__RESPONSAVEL_PRINCIPAL_FISCAL',
    number: 17,
    block: 'FISCAL',
    label: 'Responsável principal - Fiscal',
    type: 'RELACAO',
    format: 'EQUIPE',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront],
  },
  {
    key: 'FISCAL__RESPONSAVEL_SECUNDARIO_FISCAL',
    number: 18,
    block: 'FISCAL',
    label: 'Responsável secundário - Fiscal',
    type: 'RELACAO',
    format: 'EQUIPE',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront],
  },
  {
    key: 'FISCAL__FORMA_RECEBIMENTO_DOCUMENTOS',
    number: 19,
    block: 'FISCAL',
    label: 'Forma recebimento documentos',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Recebimento / organização do fluxo',
    fronts: ['FISCAL' as ComplexityFront],
    options: [
      { value: 'PLATAFORMA_INTEGRADA', label: 'Plataforma integrada', co: { FISCAL: 1 } },
      { value: 'PORTAL', label: 'Portal', co: { FISCAL: 1 } },
      { value: 'E_MAIL', label: 'E-mail', co: { FISCAL: 2 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { FISCAL: 3 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { FISCAL: 5 } },
      { value: 'ACESSO_AO_SISTEMA_DO_CLIENTE', label: 'Acesso ao sistema do cliente', co: { FISCAL: 3 } },
      { value: 'NAO_SE_APLICA', label: 'Não se aplica', notApplicable: true },
    ],
  },
  {
    key: 'FISCAL__FORMA_ENVIO_DOCUMENTOS',
    number: 20,
    block: 'FISCAL',
    label: 'Forma envio documentos',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Envio / padronização do fluxo',
    fronts: ['FISCAL' as ComplexityFront],
    options: [
      { value: 'PLATAFORMA_INTEGRADA', label: 'Plataforma integrada', co: { FISCAL: 1 } },
      { value: 'PORTAL', label: 'Portal', co: { FISCAL: 1 } },
      { value: 'E_MAIL', label: 'E-mail', co: { FISCAL: 3 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { FISCAL: 4 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { FISCAL: 5 } },
      { value: 'NAO_SE_APLICA', label: 'Não se aplica', notApplicable: true },
    ],
  },
  {
    key: 'FISCAL__FORMA_INTEGRACAO',
    number: 21,
    block: 'FISCAL',
    label: 'Forma integração',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Integração / automação',
    fronts: ['FISCAL' as ComplexityFront],
    options: [
      { value: 'AUTOMATICA_API', label: 'Automática/API', co: { FISCAL: 1 } },
      { value: 'IMPORTACAO_DE_ARQUIVO', label: 'Importação de arquivo', co: { FISCAL: 2 } },
      { value: 'ACESSO_DIRETO_AO_SISTEMA', label: 'Acesso direto ao sistema', co: { FISCAL: 2 } },
      { value: 'HIBRIDA', label: 'Híbrida', co: { FISCAL: 3 } },
      { value: 'SEM_INTEGRACAO', label: 'Sem integração', co: { FISCAL: 5 } },
    ],
  },
  {
    key: 'FISCAL__NOTA_VOLUME',
    number: 22,
    block: 'FISCAL',
    label: 'Nota Volume',
    type: 'LISTA',
    role: 'CC',
    pillar: 'Volume',
    fronts: ['FISCAL' as ComplexityFront],
    options: [
      { value: 'BAIXO', label: 'Baixo', cc: { FISCAL: 1 } },
      { value: 'MEDIO', label: 'Médio', cc: { FISCAL: 3 } },
      { value: 'ALTO', label: 'Alto', cc: { FISCAL: 5 } },
    ],
  },
  {
    key: 'FISCAL__NOTA_ATENDIMENTO',
    number: 23,
    block: 'FISCAL',
    label: 'Nota Atendimento',
    type: 'LISTA',
    role: 'AMBOS',
    pillar: 'Atendimento',
    fronts: ['FISCAL' as ComplexityFront],
    options: [
      { value: 'BAIXO', label: 'Baixo', cc: { FISCAL: 1 }, co: { FISCAL: 1 } },
      { value: 'MEDIO', label: 'Médio', cc: { FISCAL: 3 }, co: { FISCAL: 3 } },
      { value: 'ALTO', label: 'Alto', cc: { FISCAL: 5 }, co: { FISCAL: 5 } },
    ],
  },
  {
    key: 'FISCAL__NOTA_ORGANIZACAO',
    number: 24,
    block: 'FISCAL',
    label: 'Nota Organização',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Organização',
    fronts: ['FISCAL' as ComplexityFront],
    options: [
      { value: 'BAIXA', label: 'Baixa', co: { FISCAL: 5 } },
      { value: 'MEDIA', label: 'Média', co: { FISCAL: 3 } },
      { value: 'ALTA', label: 'Alta', co: { FISCAL: 1 } },
    ],
  },
  {
    key: 'FISCAL__OBSERVACOES_FISCAL',
    number: 25,
    block: 'FISCAL',
    label: 'Observações - Fiscal',
    type: 'TEXTO',
    role: 'CADASTRO',
    fronts: ['FISCAL' as ComplexityFront],
  },
  {
    key: 'CONTABIL__RESPONSAVEL_PRINCIPAL_CONTABIL',
    number: 26,
    block: 'CONTABIL',
    label: 'Responsável principal - Contábil',
    type: 'RELACAO',
    format: 'EQUIPE',
    role: 'CADASTRO',
    fronts: ['CONTABIL' as ComplexityFront],
  },
  {
    key: 'CONTABIL__RESPONSAVEL_SECUNDARIO_CONTABIL',
    number: 27,
    block: 'CONTABIL',
    label: 'Responsável secundário - Contábil',
    type: 'RELACAO',
    format: 'EQUIPE',
    role: 'CADASTRO',
    fronts: ['CONTABIL' as ComplexityFront],
  },
  {
    key: 'CONTABIL__FORMA_RECEBIMENTO_DOCUMENTOS',
    number: 28,
    block: 'CONTABIL',
    label: 'Forma recebimento documentos',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Recebimento / organização do fluxo',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'PLATAFORMA_INTEGRADA', label: 'Plataforma integrada', co: { CONTABIL: 1 } },
      { value: 'PORTAL', label: 'Portal', co: { CONTABIL: 1 } },
      { value: 'E_MAIL', label: 'E-mail', co: { CONTABIL: 2 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { CONTABIL: 3 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { CONTABIL: 5 } },
      { value: 'ACESSO_AO_SISTEMA_DO_CLIENTE', label: 'Acesso ao sistema do cliente', co: { CONTABIL: 3 } },
      { value: 'NAO_SE_APLICA', label: 'Não se aplica', notApplicable: true },
    ],
  },
  {
    key: 'CONTABIL__FORMA_ENVIO_DOCUMENTOS',
    number: 29,
    block: 'CONTABIL',
    label: 'Forma envio documentos',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Envio / padronização do fluxo',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'PLATAFORMA_INTEGRADA', label: 'Plataforma integrada', co: { CONTABIL: 1 } },
      { value: 'PORTAL', label: 'Portal', co: { CONTABIL: 1 } },
      { value: 'E_MAIL', label: 'E-mail', co: { CONTABIL: 2 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { CONTABIL: 4 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { CONTABIL: 5 } },
      { value: 'NAO_SE_APLICA', label: 'Não se aplica', notApplicable: true },
    ],
  },
  {
    key: 'CONTABIL__FORMA_INTEGRACAO',
    number: 30,
    block: 'CONTABIL',
    label: 'Forma integração',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Integração / automação',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'AUTOMATICA_API', label: 'Automática/API', co: { CONTABIL: 1 } },
      { value: 'IMPORTACAO_DE_ARQUIVO', label: 'Importação de arquivo', co: { CONTABIL: 2 } },
      { value: 'ACESSO_DIRETO_AO_SISTEMA', label: 'Acesso direto ao sistema', co: { CONTABIL: 2 } },
      { value: 'HIBRIDA', label: 'Híbrida', co: { CONTABIL: 3 } },
      { value: 'SEM_INTEGRACAO', label: 'Sem integração', co: { CONTABIL: 5 } },
    ],
  },
  {
    key: 'CONTABIL__FORMA_DE_LANCAMENTO',
    number: 31,
    block: 'CONTABIL',
    label: 'Forma de lançamento',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Automação do lançamento',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'MANUAL', label: 'Manual', co: { CONTABIL: 5 } },
      { value: 'IMPORTACAO_DE_ARQUIVO', label: 'Importação de arquivo', co: { CONTABIL: 3 } },
      { value: 'INTEGRACAO_AUTOMATICA', label: 'Integração automática', co: { CONTABIL: 1 } },
      { value: 'MISTA', label: 'Mista', co: { CONTABIL: 3 } },
    ],
  },
  {
    key: 'CONTABIL__PERIODICIDADE_DE_FECHAMENTO',
    number: 32,
    block: 'CONTABIL',
    label: 'Periodicidade de Fechamento',
    type: 'LISTA',
    role: 'AMBOS',
    pillar: 'Frequência e previsibilidade',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'MENSAL', label: 'Mensal', cc: { CONTABIL: 5 }, co: { CONTABIL: 5 } },
      { value: 'BIMESTRAL', label: 'Bimestral', cc: { CONTABIL: 4 }, co: { CONTABIL: 4 } },
      { value: 'TRIMESTRAL', label: 'Trimestral', cc: { CONTABIL: 3 }, co: { CONTABIL: 3 } },
      { value: 'QUADRIMESTRAL', label: 'Quadrimestral', cc: { CONTABIL: 3 }, co: { CONTABIL: 3 } },
      { value: 'SEMESTRAL', label: 'Semestral', cc: { CONTABIL: 2 }, co: { CONTABIL: 2 } },
      { value: 'ANUAL', label: 'Anual', cc: { CONTABIL: 1 }, co: { CONTABIL: 1 } },
      { value: 'SOB_DEMANDA_IRREGULAR', label: 'Sob demanda/Irregular', cc: { CONTABIL: 1 }, co: { CONTABIL: 1 } },
    ],
  },
  {
    key: 'CONTABIL__ULTIMO_MES_DE_CONCILIACAO',
    number: 33,
    block: 'CONTABIL',
    label: 'Último Mês de Conciliação',
    type: 'MASCARA',
    format: 'DATA',
    role: 'CADASTRO',
    pillar: 'Atraso / desempenho',
    fronts: ['CONTABIL' as ComplexityFront],
  },
  {
    key: 'CONTABIL__NOTA_VOLUME',
    number: 34,
    block: 'CONTABIL',
    label: 'Nota Volume',
    type: 'LISTA',
    role: 'CC',
    pillar: 'Volume',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'BAIXO', label: 'Baixo', cc: { CONTABIL: 1 } },
      { value: 'MEDIO', label: 'Médio', cc: { CONTABIL: 3 } },
      { value: 'ALTO', label: 'Alto', cc: { CONTABIL: 5 } },
    ],
  },
  {
    key: 'CONTABIL__NOTA_ATENDIMENTO',
    number: 35,
    block: 'CONTABIL',
    label: 'Nota Atendimento',
    type: 'LISTA',
    role: 'AMBOS',
    pillar: 'Atendimento',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'BAIXO', label: 'Baixo', cc: { CONTABIL: 1 }, co: { CONTABIL: 1 } },
      { value: 'MEDIO', label: 'Médio', cc: { CONTABIL: 3 }, co: { CONTABIL: 3 } },
      { value: 'ALTO', label: 'Alto', cc: { CONTABIL: 5 }, co: { CONTABIL: 5 } },
    ],
  },
  {
    key: 'CONTABIL__NOTA_ORGANIZACAO',
    number: 36,
    block: 'CONTABIL',
    label: 'Nota Organização',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Organização',
    fronts: ['CONTABIL' as ComplexityFront],
    options: [
      { value: 'BAIXA', label: 'Baixa', co: { CONTABIL: 5 } },
      { value: 'MEDIA', label: 'Média', co: { CONTABIL: 3 } },
      { value: 'ALTA', label: 'Alta', co: { CONTABIL: 1 } },
    ],
  },
  {
    key: 'CONTABIL__OBSERVACOES_CONTABIL',
    number: 37,
    block: 'CONTABIL',
    label: 'Observações - Contábil',
    type: 'TEXTO',
    role: 'CADASTRO',
    fronts: ['CONTABIL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__RESPONSAVEL_PRINCIPAL_PESSOAL',
    number: 38,
    block: 'PESSOAL',
    label: 'Responsável principal - Pessoal',
    type: 'RELACAO',
    format: 'EQUIPE',
    role: 'CADASTRO',
    fronts: ['PESSOAL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__RESPONSAVEL_SECUNDARIO_PESSOAL',
    number: 39,
    block: 'PESSOAL',
    label: 'Responsável secundário - Pessoal',
    type: 'RELACAO',
    format: 'EQUIPE',
    role: 'CADASTRO',
    fronts: ['PESSOAL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__QTD_FUNCIONARIOS',
    number: 40,
    block: 'PESSOAL',
    label: 'Qtd. Funcionários',
    type: 'MASCARA',
    format: 'VALOR',
    role: 'INSUMO',
    pillar: 'Volume de vínculos',
    fronts: ['PESSOAL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__QTD_PRO_LABORES',
    number: 41,
    block: 'PESSOAL',
    label: 'Qtd. Pró-labores',
    type: 'MASCARA',
    format: 'VALOR',
    role: 'INSUMO',
    pillar: 'Volume de vínculos',
    fronts: ['PESSOAL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__QTD_DOMESTICAS',
    number: 42,
    block: 'PESSOAL',
    label: 'Qtd. Domésticas',
    type: 'MASCARA',
    format: 'VALOR',
    role: 'INSUMO',
    pillar: 'Volume de vínculos',
    fronts: ['PESSOAL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__TOTAL_DE_VINCULOS',
    number: 43,
    block: 'PESSOAL',
    label: 'Total de Vínculos',
    type: 'RESULTADO',
    role: 'CC',
    pillar: 'Volume de vínculos',
    fronts: ['PESSOAL' as ComplexityFront],
  },
  {
    key: 'PESSOAL__RECEBIMENTO_DOCUMENTOS',
    number: 44,
    block: 'PESSOAL',
    label: 'Recebimento documentos',
    type: 'LISTA',
    role: 'CO',
    // Papel corrigido em relação à planilha: as notas de CO estão
    // preenchidas mas os marcadores diziam 'Cadastro / Controle'.
    // Decisão de 09/09/2026, pendente de confirmação formal.
    roleOverridesTemplate: true,
    fronts: ['PESSOAL' as ComplexityFront],
    options: [
      { value: 'PLATAFORMA_INTEGRADA', label: 'Plataforma integrada', co: { PESSOAL: 1 } },
      { value: 'PORTAL', label: 'Portal', co: { PESSOAL: 2 } },
      { value: 'E_MAIL', label: 'E-mail', co: { PESSOAL: 3 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { PESSOAL: 3 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { PESSOAL: 5 } },
      { value: 'ACESSO_AO_SISTEMA_DO_CLIENTE', label: 'Acesso ao sistema do cliente', co: { PESSOAL: 3 } },
      { value: 'NAO_SE_APLICA', label: 'Não se aplica', notApplicable: true },
    ],
  },
  {
    key: 'PESSOAL__RECEBIMENTO_PONTO',
    number: 45,
    block: 'PESSOAL',
    label: 'Recebimento ponto',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Recebimento do ponto',
    fronts: ['PESSOAL' as ComplexityFront],
    options: [
      { value: 'SISTEMA_DE_PONTO_INTEGRADO', label: 'Sistema de ponto integrado', co: { PESSOAL: 1 } },
      { value: 'ARQUIVO_EXPORTACAO', label: 'Arquivo/Exportação', co: { PESSOAL: 2 } },
      { value: 'PLANILHA', label: 'Planilha', co: { PESSOAL: 3 } },
      { value: 'E_MAIL', label: 'E-mail', co: { PESSOAL: 3 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { PESSOAL: 4 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { PESSOAL: 5 } },
      { value: 'NAO_UTILIZA_CONTROLE_DE_PONTO', label: 'Não utiliza controle de ponto', notApplicable: true },
    ],
  },
  {
    key: 'PESSOAL__ENVIO_DOCUMENTOS',
    number: 46,
    block: 'PESSOAL',
    label: 'Envio documentos',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Envio / padronização do fluxo',
    fronts: ['PESSOAL' as ComplexityFront],
    options: [
      { value: 'PLATAFORMA_INTEGRADA', label: 'Plataforma integrada', co: { PESSOAL: 1 } },
      { value: 'PORTAL', label: 'Portal', co: { PESSOAL: 2 } },
      { value: 'E_MAIL', label: 'E-mail', co: { PESSOAL: 4 } },
      { value: 'MENSAGERIA', label: 'Mensageria', co: { PESSOAL: 4 } },
      { value: 'MANUAL_FISICO', label: 'Manual/Físico', co: { PESSOAL: 5 } },
      { value: 'NAO_SE_APLICA', label: 'Não se aplica', notApplicable: true },
    ],
  },
  {
    key: 'PESSOAL__NOTA_ATENDIMENTO',
    number: 47,
    block: 'PESSOAL',
    label: 'Nota Atendimento',
    type: 'LISTA',
    role: 'AMBOS',
    pillar: 'Atendimento',
    fronts: ['PESSOAL' as ComplexityFront],
    options: [
      { value: 'BAIXO', label: 'Baixo', cc: { PESSOAL: 1 }, co: { PESSOAL: 1 } },
      { value: 'MEDIO', label: 'Médio', cc: { PESSOAL: 3 }, co: { PESSOAL: 3 } },
      { value: 'ALTO', label: 'Alto', cc: { PESSOAL: 5 }, co: { PESSOAL: 5 } },
    ],
  },
  {
    key: 'PESSOAL__NOTA_ORGANIZACAO',
    number: 48,
    block: 'PESSOAL',
    label: 'Nota Organização',
    type: 'LISTA',
    role: 'CO',
    pillar: 'Organização',
    fronts: ['PESSOAL' as ComplexityFront],
    options: [
      { value: 'BAIXA', label: 'Baixa', co: { PESSOAL: 5 } },
      { value: 'MEDIA', label: 'Média', co: { PESSOAL: 3 } },
      { value: 'ALTA', label: 'Alta', co: { PESSOAL: 1 } },
    ],
  },
  {
    key: 'PESSOAL__NOTA_ROTATIVIDADE',
    number: 49,
    block: 'PESSOAL',
    label: 'Nota Rotatividade',
    type: 'LISTA',
    role: 'CC',
    pillar: 'Rotatividade',
    fronts: ['PESSOAL' as ComplexityFront],
    options: [
      { value: 'BAIXA', label: 'Baixa', cc: { PESSOAL: 1 } },
      { value: 'MEDIA', label: 'Média', cc: { PESSOAL: 3 } },
      { value: 'ALTA', label: 'Alta', cc: { PESSOAL: 5 } },
    ],
  },
  {
    key: 'PESSOAL__OBSERVACOES_PESSOAL',
    number: 50,
    block: 'PESSOAL',
    label: 'Observações - Pessoal',
    type: 'TEXTO',
    role: 'CADASTRO',
    fronts: ['PESSOAL' as ComplexityFront],
  },
];

// Faixas do Total de Vínculos (campo calculado da frente Pessoal).
// Definidas na planilha, coluna NOTA CC PESSOAL do campo 43.
export const LINK_COUNT_BANDS = [
  { max: 10, score: 1 },
  { max: 50, score: 3 },
  { max: Infinity, score: 5 },
];
